### PR TITLE
magrittr (dplyr) pipe and other specials

### PR DESCRIPTION
**Pull request by rsaporta**
Added commonly used pipe from the magrittr package (used in dplyr)
  %>% 
  %<>% 
  %T>% 
  %$%

### CODE REVIEW

**Comment by randy3k** [comment]
👍

**Comment by randy3k** [comment]
Just want to let you know, in `xml` files, `&lt;` and `&gt;` should be used instead of `<` and `>`. :)

**Comment by rsaporta** [comment]
great point.  I see you updated it already, thanks. 

By the way, do they need to be escaped for regex-sake? 
eg  `\&gt;` instead of `&gt;`?

**Comment by randy3k** [comment]
In regex, `<` and `>` do not need to be escaped.

**Comment by rsaporta** [comment]
whoops, brain was wrapped around `[` `]`

**Pull request merged**
