### PR TITLE
get_body - use deparse and collapse longer bodies

### PR DESCRIPTION
**Pull request by rsaporta**
Two changes to `get_body()`
* using `deparse()` instead of `capture.output()` (The latter creates, writes to and then reads from a temp file every iteration)
* combine longer methods into a single line while removing superfluous whitespace

### CODE REVIEW

**Comment by rsaporta** [comment]
Compare for example `abbreviate` (the first function in `base`): 
                
    ## Previously
    "abbreviate" : "abbreviate(names.arg, minlength = 4L, use.classes = TRUE, dot = FALSE, ",

    ## Current
    "abbreviate" : "abbreviate(names.arg, minlength = 4L, use.classes = TRUE, dot = FALSE, strict = FALSE, method = c(\"left.kept\", \"both.sides\")) ",

**Comment by randy3k** [comment]
Merged. Thanks.

**Comment by randy3k** [comment]
I am looking a more user friendly way to generate the package and syntax files. Any suggestions?

**Comment by rsaporta** [comment]
What details specifically do you need to extract? Just function name and prototype?

**Pull request closed without merging**
