### PR TITLE
Tm language additions

### PR DESCRIPTION
**Pull request by rsaporta**
Minor updates to the R Extended.tmLanguage file 
Namely: 
   * Rprofile.site  file type
   * NA Constants
   * foreach keywords
   * data.table keywords

### CODE REVIEW

**Comment by randy3k** [comment]
Thx for your PR. I think that `NA_*` constants are good. However, I am not quite sure about the other three commits.

[`.site`]:   `.site`is not a r-specified file extension, it may not be a good idea to always apply R syntax to `.site` files.

[`foreach` and `data.table`]:   the supported functions are actually generated by `script.R`, and I have restricted length of the name of functions to be more than 3 to avoid mis-highlighting. I am happy to include `foreach` in the syntax, but I do want to keep the minimum function name restriction.

**Comment by rsaporta** [comment]
[`.site`]:  I haven't found many other programs using `.site` except for Adobe GoLive, but then again, not too many `R` users use it either.  So not including shouldn't affect too many people. 

[`foreach`]:  That would be great to include it, especially for the special characters (`%dopar%` etc)

Regarding the three-character minimum, were you finding a lot of mis-highlighting?  The minimum unfortunately crops out  `c()` and `cat()`  which I would guess appear quite often.

**Comment by randy3k** [comment]
NA Constants and foreach operators added.

**Comment by randy3k** [comment]
I think it could be closed now given the new functionality of customizing syntax highlight and auto completions. https://github.com/randy3k/R-Box#autocompletions-and-status-bar-hints

**Comment by rsaporta** [comment]
agreed

**Pull request closed without merging**
